### PR TITLE
Support post-award browser tests

### PR DESCRIPTION
**Pull request by samuelhwilliams**
- Pull in COOKIE_DOMAIN from env, if defined, even in dev environment
- Add mock data for post award browser tests to generate magic links

FPASF-287

### CODE REVIEW

**Comment by gidsg** [comment]
> Add mock data for post award browser tests to generate magic links

Is the need here just to have stable identifiers we can use? Is there a reason we don't use the existing ones? Would be good to have some rationale in the PR description/commit message?

**Comment by samuelhwilliams** [comment]
We add new mock data here because:

- We can set a custom fund name, which makes it clear what the purpose
  of the mock data is (i.e. we're using it for post-award's end-to-end
  tests; basically an implicit acknowledge that this is a bit of a
  'hack').
- The magic link flows the end-to-end tests use pass `short_name=True`,
  but the existing mock data has `short_name=False` - so they actually
  don't resolve and no data is returned. So we need new mock data either
  way.

---

I've added this into the commit msg 👍

**Review by gidsg — APPROVED** [review]
LGTM 👍

**Review by MarcUsher — APPROVED** [review]
Looks good - I feel like there's been lots you and Albert have been discovering with Authenticator recently, could be a good one to spend some time talking about at the next tech chat?

**Comment by samuelhwilliams** [comment]
> Looks good - I feel like there's been lots you and Albert have been discovering with Authenticator recently, could be a good one to spend some time talking about at the next tech chat?

Yeah, I was hoping to chat some stuff through at the tech chat yesterday but that other meeting happened. Next week I'll try to say something 👍

**Pull request merged**
