### PR TITLE
FS-4073 4074 EOI fixes

### PR DESCRIPTION
**Pull request by RamuniN**
https://dluhcdigital.atlassian.net/browse/FS-4073
https://dluhcdigital.atlassian.net/browse/FS-4074

### Description
- Added `EOI` landing page
- Added modifications for `EOI` in email page

linked PR https://github.com/communitiesuk/funding-service-design-frontend/pull/535

### CODE REVIEW

**Review by adamdavies1 — COMMENTED** [review]
Fix failing tests

**Comment by RamuniN** [comment]
> Fix failing tests
@adamdavies1 
Unit tests are successfully running. E2E tests fail as it is on Dev environment

**Review by cyrusdobbs — APPROVED** [review]
LGTM from post-award pov

**Review by adamdavies1 — APPROVED** [review]
LGTM - Pre Award

**Pull request merged**
